version: '3.4'

services:
  masstransit.gettingstarted.worker:
    image: ${DOCKER_REGISTRY-}masstransitgettingstartedworker
    build:
      context: .
      dockerfile: MassTransit.GettingStarted.Worker/Dockerfile
    depends_on:
      - rabbitmq
    networks:
      - mass-transit-getting-started

  masstransit.gettingstarted.consumer:
    image: ${DOCKER_REGISTRY-}masstransitgettingstartedconsumer
    build:
      context: .
      dockerfile: MassTransit.GettingStarted.Consumer/Dockerfile
    depends_on:
      - rabbitmq
    networks:
      - mass-transit-getting-started

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - mass-transit-getting-started

networks:
  mass-transit-getting-started:
    driver: bridge